---
collections:
  #- name: ansible.controller
  - name: infrastructure_engineering.utilities
  #- name: redhat.rhel_system_roles
  #- name: community.general
  - name: citrix.adc
  #- name: azure.azcollection
