---
- hosts: localhost
  gather_facts: true
  tasks:
  - name: test api connection
    ansible.builtin.uri:
        url: "https://aap24.local.net/api/v2/users/"
        method: GET
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: False
        return_content: yes
        force_basic_auth: yes

  - name: View password
    debug: ansible_password
  
        #headers:
         # Content-Type: "application/json"
         # Accept: "application/json"
        #body_format: json
     # register: Login
