---
- name: test copy function
  hosts:  all
  gather_facts: False
  # become: yes
  tasks:
  - name: Copy a file to remote servers
       #become: true
     copy:
       src: /uploads/testfile
       dest: /home/grs/testfile
       
