---
- name: test copy function
  hosts:  all
  gather_facts: False
  # become: yes
  tasks:
  - name: Copy a file to remote servers
    ansible.builtin.copy:
       src: /uploads/testfile
       dest: /root/testfile
       remote_src: false
