---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: create new inventory
      ansible.controller.inventory:
        name: TestInv
        organization: Default
        state: present
        controller_host: aap24.local.net
        controller_username: root
        controller_password: redhat
