---
- hosts: localhost
  gather_facts: false
  vars:
    errorScenario: "Unable to get project id using NFVD api"
  
  tasks:
    - name: rescue - debug errorScenario
      debug:
        msg: "{{ errorScenario }}"
