---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: rescue - set fail message in case of any issues in getting project name
      set_fact:
        errorScenario: ""

    - name: rescue - debug errorScenario
      debug:
        msg: "{{ errorScenario }}" 
