---
- hosts: localhost
  gather_facts: false
  #vars:
    #errorScenario: "Unable to get project id using NFVD api"
  
  tasks:
    - name: set variables
      set_fact:
        errorScenario: "hello"
      
    - debug:
        msg: "{{ errorScenario }}"

