---
- hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: test whoami
      ansible.builtin.shell:  whoami
    
    - name: dnf install package
      ansible.builtin.dnf:
        name: tmux
        state: present
    
    - debug: 
        var: {{ package }}
  
        
