---
- hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: test whoami
      ansible.builting.shell:  whoami
    
    - name: dnf install package
      ansible.builtin.dnf:
        name: tmux
        state: present
  
        
