---
- hosts: all
  gather_facts: no
    
  tasks:
  - name: Send notification email
    community.general.mail:
          from: bubba@bubbagumpshrimp.com
          to: gump@trump.gov
          subject: Server Deployed, plese refer to the body message.
          body: "scom_deployment_log_file.stdout"
    ignore_errors: yes
