---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: output uptime
    netbox
      plugin: netbox.netbox.nb_inventory
      api_endpoint: http://localhost:8000
      validate_certs: false
