---
- hosts: localhost
  serial: 1
  #remote_user: awx
  gather_facts: false
  tasks:
  - name: "Ensure content view version 11.0 doesn't exist"
    redhat.satellite.content_view_version:
      server_url: "https://rhel91.local.net"
      username: "admin"
      password: "redhat"
      organization: "My_Organization"
      content_view: "test"
      version: "11.0"
      state: absent
      validate_certs: false
