---
- name: Setup Apache
  hosts: all
  #become: true

  tasks:
  - name: create file for rsync test
    ansible.builtin.file:
      path: /payload/rsyncCheck.txt
      state: touch
      mode: '0755'
  - name: rsync connection test
    ansible.posix.synchronize:
      src: /payload/rsyncCheck.txt
      dest: /tmp/rsyncCheck.txt
