---
- name: Setup Apache
  hosts: all
  gather_facts: false
  #become: true

  tasks:
  - name: create file for rsync test
    ansible.builtin.file:
      path: rsyncCheck.txt
      state: touch
      mode: '0755'
  - name: rsync connection test
    ansible.posix.synchronize:
      src: rsyncCheck.txt
      dest: /dest/rsyncCheck.txt
    delegate_to: "{{ inventory_hostname }}"
