---
- name: Test become
  hosts: all
  gather_facts: no
  become: true
  become_user: joe
  become_method: su
  become_exe: sudo su -

  tasks:
  - name: verify the id
    shell: 'whoami'
    register: cli_out

  - debug: var=cli_out.stdout_lines
