---
- hosts: all
  #hosts: all
  #remote_user: awx
  gather_facts: false
  tasks:
  #- name: Store stat
  #  ansible.builtin.set_stats:
  #    data:
  #      mystat: "First stat"

  - name: Store fact
    ansible.builtin.set_fact:
      data:
        myfact: "First fact"

  - debug:
      var: myfact
