---
- name: Test become
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo
  #become_exe: sudo su -

  tasks:
  - name: verify the id
    shell: ls /root
    register: cli_out

  - debug: var=cli_out.stdout_lines
