---
- hosts: all
  gather_facts: false
  tasks:
    - name: yum update system
      ansible.builtin.yum:
        list: updates
        #name: '*'
        state: latest
        update_cache: true
        exclude: kernel*
