---
- hosts: all
  tasks:
    - name: yum update system
      ansible.builtin.yum:
        list: updates
#        name: 'kernel'
        state: latest
        update_cache: true
        exclude: kernel*
