---
- hosts: all
  #hosts: all
  #remote_user: awx
  gather_facts: false
  tasks:
  - name: output uptime
    #shell: whoami
    shell: uptime
    register: command_output
    
  - debug: 
      var: myname
 
  
