---
- hosts: all
  gather_facts: false
  tasks:
  - name: test uptime
    shell: uptime
    register: command_output
    
  - debug: 
      var: command_output.stdout_lines
 # - name: store facts
  #  ansible.builtin.setup:
    
  
