---
- hosts: localhost 
  gather_facts: false
  tasks:
  - name: output uptime
    shell: ls -la
    register: command_output
    
  - debug: 
      var: command_output

  - name: pause
    ansible.builtin.pause:
      minutes: 10
  
    
