---
- hosts: all
  no_log: true
  gather_facts: true
  tasks:
  - name: output uptime
    shell: uptime
    register: command_output
    
  - debug: 
      msg: "The value is {{ command_output }}"

    
