---
- hosts: all
  gather_facts: true
  tasks:
  - name: test uptime
    shell: uptime
    #command: kjskjhs
    register: command_output
    
  - debug: 
      var: command_output.stdout_lines
 # - name: store facts
  #  ansible.builtin.setup:
    
  
