---
- hosts: all
  gather_facts: false
  tasks:
  - name: output uptime
    shell: uptime
    #register: command_output
  - name: list files
    shell: ls -la /myfiles
    register: command_output
  - debug: 
      var: command_output
