---
- hosts: all
  gather_facts: false
  tasks:
  - name: output hostname
    shell: hostname
    #command: kjskjhs
    register: command_output
    
  - debug: 
      var: command_output.stdout_lines
 
  - name: ssh into another host
    shell:  'sshpass -p "redhat" ssh -o StrictHostKeyChecking=no root@aap23.local.net "hostname"'   
  
