---
- hosts: all
  serial: 1
  #remote_user: awx
  gather_facts: true
  tasks:
  - name: Update kerberos
    shell:  |
      echo "includedir /etc/krb5.conf.d/" > /etc/krb5.conf
      cat /etc/krb5.conf
    delegate_to: localhost
    register: out_kerb
  - name: sleep
    shell: sleep 6
  - name: output uptime
    #shell: whoami
    shell: uptime
    register: command_output
    #when: '"Linux" in ansible_run_tags.stdout'
    #tags: Linux
    
  - debug: 
      var: out_kerb
 
    
