---
- hosts: all
  serial: 1
  #remote_user: awx
  gather_facts: true
  tasks:
  - name: output uptime
    #shell: whoami
    shell: uptime
    register: command_output
    #when: '"Linux" in ansible_run_tags.stdout'
    #tags: Linux
    
  - debug: 
      var: command_output
 
    
