- name: Listen for events on kafka
  hosts: 127.0.0.1

  sources:
    - ansible.eda.kafka:
        host: 10.0.78.116
        port: 9092
        topic: kafka-test-topic
        groupId: "netops"
        
    
  rules:
    - name: kafka
      condition:
        any:
          - event.payload is defined
          - event.body is defined
      #condition: event.body.message == "HELLO"
      #condition: event.body.message != ""         #<------ Neither condition works
      
      action:
        debug:
          msg: "You are good!"
        
