- name: Listen for events on kafka
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: 10.0.78.116
        port: 9092
        topic: kafka-test-topic
        
    
  rules:
    - name: kafka
      #condition: event.body.message == "HELLO"
      condition: event.body.message != ""         #<------ Neither condition works
      action:
        debug:
          msg: "You are good!"
        
