- name: Basic webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8000

  rules:
    - name: Capture payload to fact variable
      condition: event.payload.message == "CRITICAL"    #and event.payload.meta.hosts == "node761.local.net"
      action:
        run_job_template:
          name: "Target Check - vCenter"
          organization: "Jamf-IT"
