- name: webcheck of file server
  hosts: web
  sources:
    - ansible.eda.url_check:
        urls:
          - http://asgard.local.net
        delay: 10
  rules:
    - name: Web site is up
      condition: event.url_check.status == "up"
      ##Define the action that should be taken
      action:
        run_job_template:
          name: uptime
          organization: Default
          
    - name: Web site is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: version
          organization: Default
