---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: service|fault state(httpd)
      condition: event.payload.message == "CRITICAL"

  ## Define the action we should take should the condition be met

      action:
        # https://access.redhat.com/solutions/7024714
        #run_playbook:
          #name: aap_basic_service_recovery_httpd.yml

        run_job_template:
          name: version
          organization: Default
          job_args:
           #extra_vars:
              limit: {{ event.payload.meta.hosts }}
