---
- name: Listen for events on a webhook
  hosts: all


# curl call to trigger the event

# curl --header "Content-Type: application/json"  --request POST   --data '{"message":"CRITICAL", "event":{"fields":{"source":"node891.local.net"}}}'   http://eda24.local.net:5000/payload

# make sure that you have 'limit' set to prompt for update on the template

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.insert_hosts_to_meta:
            host_path: payload.event.fields.source

  ## Define the conditions we are looking for

  rules:
    - name: service|fault state(httpd)
      condition: event.payload.message == "CRITICAL"

       
  ## Define the action we should take should the condition be met

      action:
        run_job_template:
          name: uptime
          organization: Default
          
